### PR TITLE
Fix lobby countdown logic, add boot participant confirmation, and improve experiment creation redirect.

### LINKED ISSUE #248: Add verification step before "booting"

### PR DESCRIPTION
**Pull request by cjqian**
Fixes #248 #182

### CODE REVIEW

File: frontend/src/components/stages/transfer_view.ts [hunk 1]
```diff
@@ -48,36 +54,57 @@ export class TransferView extends MobxLitElement {
 
     return html`
       <stage-description .stage=${this.stage}></stage-description>
-      ${this.renderCountdown()}
-      ${this.renderOverlay()}
+
+      <div>
+        Please wait while we transfer you to the next stage of the experiment.
```
Comment (vivtsai) [inline frontend/src/components/stages/transfer_view.ts:59]: Does it make sense to not hardcode text here since experimenters can customize it via the stage description?

File: frontend/src/components/stages/transfer_view.ts [hunk 2]
```diff
@@ -48,36 +54,57 @@ export class TransferView extends MobxLitElement {
...
+    const seconds = this.timeRemainingSeconds % 60;
+
+    const timeColor = getRgbColorInterpolation(
+      '#A8DAB5', // Green
+      '#FBA9D6', // Red
+      this.timeRemainingSeconds,
+      this.stage?.timeoutSeconds
+    );
+    return html` <div>
+      If the transfer cannot be completed, the experiment will end in:
```
Comment (vivtsai) [inline frontend/src/components/stages/transfer_view.ts:92]: We should only render this message if `this.stage.enableTimeout` is true. (Actually, we should probably not render a countdown at all if timeout is not enabled.)

Comment (cjqian) [reply frontend/src/components/stages/transfer_view.ts:92]: Makes sense, changed. (This was the case before, but we were checking on `countdownSeconds` which is set if `enableTimeout`).

**Review by vivtsai — APPROVED** [review]
