### PR TITLE
Make minor updates to experimenter dashboard UX and fix participant view bugs

### LINKED ISSUE #256: Move "Delete experiment" button to action bar

### PR DESCRIPTION
**Pull request by vivtsai**
Fixes #256 #437 #436 #440

Frontend-only changes.

### CODE REVIEW

File: frontend/src/components/experimenter/experimenter_panel.ts [hunk 1]
```diff
@@ -535,10 +561,38 @@ export class Panel extends MobxLitElement {
...
+        color="error"
+        variant="outlined"
+        ?disabled=${!this.experimentManager.isCreator}
+        @click=${() => {
+          const isConfirmed = window.confirm(
+            `Are you sure you want to delete this experiment?`
+          );
+          if (!isConfirmed) return;
+
+          this.analyticsService.trackButtonClick(ButtonClick.EXPERIMENT_DELETE);
```
Comment (cjqian) [inline frontend/src/components/experimenter/experimenter_panel.ts:576]: Nit: Format spacing for cleanliness?

File: frontend/src/components/participant_view/participant_view.ts [hunk 2]
```diff
@@ -181,7 +178,18 @@ export class ParticipantView extends MobxLitElement {
       !this.participantService.canAccessStage(stage.id) &&
       !this.authService.isExperimenter
     ) {
-      return html`<div class="content">Stage not available yet</div>`;
+      return html`
+        <div class="content">
+          <div>Stage not available yet</div>
+          <pr-button @click=${() => {
+            this.participantService.setCurrentStageView(
+              this.participantService.profile?.currentStageId ?? undefined
```
Comment (cjqian) [inline frontend/src/components/participant_view/participant_view.ts:186]: Maybe instead of this, only render the button if ...currentStageId is defined?

**Review by cjqian — APPROVED** [review]

File: frontend/src/components/participant_view/participant_view.ts (hunk 2 above)
Comment (vivtsai) [reply frontend/src/components/participant_view/participant_view.ts:186]: If it's undefined, it will route to the landing view (e.g., "start experiment" button or anything else shown based on the participant's status)
