### PR TITLE
Fix chip negotiation payout/offer calculations and hardcoded chip values

### LINKED ISSUE #365: Update payout to amount over baseline bonus

### PR DESCRIPTION
**Pull request by cjqian**
Fix #365

### CODE REVIEW

File: frontend/src/components/stages/payout_summary_view.ts [hunk 1]
```diff
@@ -112,15 +116,28 @@ export class PayoutView extends MobxLitElement {
...
 
   private renderChipPayoutItemResult(
     item: ChipPayoutItemResult,
     currency: PayoutCurrency
   ) {
+    const getInitialTotal = () => {
+      let total = 0;
+      for (const result of item.chipResults) {
+        let quantity = 0;
+        if (result.chip.name.includes('red')) {
```
Comment (vivtsai) [inline frontend/src/components/stages/payout_summary_view.ts:130]: can we add a TODO to generalize this later? the initial chips should really be based on the chip stage's configuration (i.e., ChipStageConfig has a ChipItem list that specifies the starting quantities), not custom variables

**Review by vivtsai — APPROVED** [review]
