### PR TITLE
Fix playtest issues with stage access, setup

### LINKED ISSUE #241: Reveal stage should only add options for surveys before it

### PR DESCRIPTION
**Pull request by cjqian**
Fixes #241 

* Disable editing "Wait for all participants" in reveal stage under specific conditions.
* Only allow revealing preceding stages (#241).
* Get rid of lock overlay on transfer stage.
* Font improvements.

### CODE REVIEW

File: frontend/src/components/stages/reveal_editor.ts [hunk 1]
```diff
@@ -44,25 +42,58 @@ export class RevealEditor extends MobxLitElement {
...
+          (expStage) => expStage.id === stage.id
+        );
+        return stageIndex < currentStageIndex;
+      });
+
+      return filteredStages;
+    };
+
+    const stageOptions = getStageOptions();
+    if (stageOptions.length === 0) {
```
Comment (vivtsai) [inline frontend/src/components/stages/reveal_editor.ts:78]: Instead of rendering twice, can we wrap the tooltip around the main return statement and set tooltip text to empty (which means no tooltip will render) if disabled?

File: frontend/src/components/stages/reveal_editor.ts [hunk 2]
```diff
@@ -44,25 +42,58 @@ export class RevealEditor extends MobxLitElement {
...
     `;
   }
 
   private renderAddMenu() {
     if (!this.stage) return nothing;
 
-    const stageOptions = getStagesWithReveal(this.experimentEditor.stages).filter(
-      stage => stage.id !== this.stage?.id
-    );
+    // Get all stages with a reveal stage.
```
Comment (vivtsai) [inline frontend/src/components/stages/reveal_editor.ts:54]: Nit: duplicate lines 54, 55

File: frontend/src/components/stages/reveal_editor.ts [hunk 3]
```diff
@@ -44,25 +42,58 @@ export class RevealEditor extends MobxLitElement {
...
+    // Get all stages with a reveal stage.
+    const getStageOptions = () => {
```
Comment (vivtsai) [inline frontend/src/components/stages/reveal_editor.ts:56]: Nit: Make this a utils function (as it's not component or state reliant)?

File: frontend/src/components/progress/progress_stage_waiting.scss [hunk 4]
```diff
@@ -51,7 +51,8 @@ h2 {
   @include common.flex-column-align-center;
   flex-wrap: wrap;
   gap: common.$spacing-medium;
-  max-width: 80px;
+  max-width: 100px;
   overflow-wrap: anywhere;
   text-align: center;
-}
\ No newline at end of file
+  font-size: var(--md-sys-typescale-body-small-font-size);
```
Comment (vivtsai) [inline frontend/src/components/progress/progress_stage_waiting.scss:57]: Instead of setting font size, include a font bundle (which will also adjust line height, spacing, etc.), e.g., `@include typescale.body-small);`

File: frontend/src/components/stages/base_stage_editor.ts [hunk 5]
```diff
@@ -129,16 +129,90 @@ export class BaseStageEditorComponent extends MobxLitElement {
     `;
   }
 
+  private shouldDisableWaitForAllParticipants(): boolean {
```
Comment (vivtsai) [inline frontend/src/components/stages/base_stage_editor.ts:132]: Can you make this a utils function that takes in list of stages, reveal stage ID?

File: frontend/src/components/stages/base_stage_editor.ts [hunk 6]
```diff
@@ -129,16 +129,90 @@ export class BaseStageEditorComponent extends MobxLitElement {
...
-      this.experimentEditor.updateStage({ ...this.stage, progress });
+      const progress: StageProgressConfig = {
+        ...this.stage.progress,
+        waitForAllParticipants: !waitForAllParticipants,
+      };
+      this.experimentEditor.updateStage({...this.stage, progress});
     };
 
+    if (this.shouldDisableWaitForAllParticipants()) {
+      if (!waitForAllParticipants) {
```
Comment (vivtsai) [inline frontend/src/components/stages/base_stage_editor.ts:189]: I don't think it makes sense to update the wait bit on render (for instance, what if you never click on the stage?). Can we instead add the setting waitForAllParticipants logic when addStage (appending a new stage) or setStages (setting a list of stages) in experimentEditor is called?

File: frontend/src/components/stages/base_stage_editor.ts [hunk 7]
```diff
@@ -129,16 +129,90 @@ export class BaseStageEditorComponent extends MobxLitElement {
...
-      const progress: StageProgressConfig = { ...this.stage.progress, waitForAllParticipants: !waitForAllParticipants };
-      this.experimentEditor.updateStage({ ...this.stage, progress });
+      const progress: StageProgressConfig = {
+        ...this.stage.progress,
+        waitForAllParticipants: !waitForAllParticipants,
+      };
+      this.experimentEditor.updateStage({...this.stage, progress});
     };
 
+    if (this.shouldDisableWaitForAllParticipants()) {
```
Comment (vivtsai) [inline frontend/src/components/stages/base_stage_editor.ts:188]: Instead of rendering twice (in this if statement and below), can we just have the main statement and conditionally set render the warning, set disabled, etc.?

**Comment by vivtsai** [comment]
Thanks for the quick turnaround on these! I left some comments, mainly re: moving calculations that are not component/state dependent to utils (maybe `experiment.utils` or a new `stage.utils`), setting waitForAllParticipants logic in the correct spot, and combining "if" renders with default renders so that things like `<md-checkbox></md-checkbox` don't need to be set up twice/kept in sync.

File: frontend/src/components/stages/reveal_editor.ts (hunk 1 above)
Comment (cjqian) [reply frontend/src/components/stages/reveal_editor.ts:78]: Done.

File: frontend/src/services/experiment.editor.ts [hunk 8]
```diff
@@ -112,30 +116,35 @@ export class ExperimentEditor extends Service {
...
-    const index = this.stages.findIndex(stage => stage.id === newStage.id);
+    const index = this.stages.findIndex((stage) => stage.id === newStage.id);
     if (index >= 0) {
       this.stages[index] = newStage;
     }
   }
 
   setStages(stages: StageConfig[]) {
-    this.stages = stages;
+    for (let stage of stages) {
```
Comment (vivtsai) [inline frontend/src/services/experiment.editor.ts:134]: set this.stages = [] first! I can push a fix for this

Comment (vivtsai) [reply frontend/src/services/experiment.editor.ts:134]: Also, my bad - I realized we actually need to do the mustWait whenever stages are edited as well. Pushing a fix for this.

**Review by vivtsai — APPROVED** [review]
